# =============================================================================
# Единый docker-compose для всего кластера
# =============================================================================
# Запуск: docker compose up -d
# Остановка: docker compose down
# =============================================================================

include:
  - postgres/docker-compose.yml
  - docker/docker-compose.yml
  - monitoring/docker-compose.yml
