all:
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
    ansible_python_interpreter: /usr/bin/python3

  children:
    haproxy:
      hosts:
        haproxy-1:
          ansible_host: 10.0.10.10
        haproxy-2:
          ansible_host: 10.0.10.11

    servers_1c:
      hosts:
        1c-1:
          ansible_host: 10.0.20.11
        1c-2:
          ansible_host: 10.0.20.12

    postgres:
      hosts:
        pg-primary:
          ansible_host: 10.0.30.21
          pg_role: primary
        pg-replica:
          ansible_host: 10.0.30.22
          pg_role: replica

    monitoring:
      hosts:
        mon-1:
          ansible_host: 10.0.40.31
